language: python

branches:
  only:
    - master

sudo: false

addons:
  apt:
    packages:
    - libdb-dev

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -U pip setuptools wheel
  - pip install -U tox-travis coveralls

script:
  - tox

after_success:
  - coveralls
