language: python

sudo: false

addons:
  apt:
    packages:
    - libdb-dev

env:
  global:
    - ZARR_TEST_ABS=1
    - ZARR_TEST_MONGO=1
    - ZARR_TEST_REDIS=1

services:
  - docker
  - redis-server
  - mongodb

matrix:
  include:
    - python: 3.6
      env: BUILD_DOCS='true'
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true
      env: MYPY_CHECK='true'

before_install:
  - docker pull arafato/azurite
  - mkdir ~/blob_emulator
  - docker run -e executable=blob -d -t -p 10000:10000 -v ~/blob_emulator:/opt/azurite/folder arafato/azurite
before_script:
    - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

install:
  - pip install -U pip setuptools wheel tox-travis mypy codecov

script:
  - tox
  - if [[ $BUILD_DOCS == 'true' ]]; then tox -e docs; fi
  - if [[ $MYPY_CHECK == 'true' ]]; then mypy zarr; fi

after_success:
  - codecov
