language: python

branches:
  only:
    - master

sudo: false

addons:
  apt:
    packages:
      - liblzma-dev

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -U tox-travis coveralls pip setuptools wheel
  - pip install -r requirements_dev.txt
  - python setup.py build_ext --inplace

script:
  - tox

after_success:
  - coveralls
