language: python

branches:
  only:
    - master

sudo: false

addons:
  apt:
    packages:
    - libdb-dev

env:
  global:
    - ZARR_TEST_ABS=1
    - ZARR_TEST_MONGO=1
    - ZARR_TEST_REDIS=1

services:
  - docker
  - redis-server
  - mongodb

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - docker pull arafato/azurite
  - mkdir ~/blob_emulator
  - docker run -e executable=blob -d -t -p 10000:10000 -v ~/blob_emulator:/opt/azurite/folder arafato/azurite
before_script:
    - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

install:
  - pip install -U pip setuptools wheel tox-travis coveralls

script:
  - tox

after_success:
  - coveralls
