environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\build.cmd"

  matrix:

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -rrequirements_test.txt"
  - "%PYTHON%\\python.exe -m pip install -rrequirements.txt"
  - git submodule update --init --recursive

build: off

test_script:
  - "%CMD_IN_ENV% python setup.py build_ext --inplace"
  - "%CMD_IN_ENV% python -m nose -v"

after_test:
  - "%CMD_IN_ENV% python setup.py bdist_wheel"

artifacts:
  - path: dist\*
