environment:

  matrix:

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -rrequirements_test.txt"
  - "%PYTHON%\\python.exe -m pip install -rrequirements.txt"

build: off

test_script:
  - "build.cmd %PYTHON%\\python.exe setup.py build_ext --inplace"
  - "build.cmd %PYTHON%\\python.exe -m nose -v"

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
