# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6.9' , 3.7, 3.8]
        numpy_version: ['==1.16.4', '']
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@master
      with:
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    # Runs a set of commands using the runners shell
    - name: Create Conda environment with the rights deps
      shell: "bash -l {0}"
      run: |
        conda create -n zarr-env python==${{matrix.python-version}} bsddb3 numcodecs==0.6.4 lmdb pip
    - name: Install dependencies
      shell: "bash -l {0}"
      run: |
        conda activate zarr-env
        python -m pip install --upgrade pip
        python -m pip install -U pip setuptools wheel codecov
        python -m pip install -rrequirements_dev_minimal.txt numpy${{ matrix.numpy_version}} -rrequirements_dev_optional.txt
        python -m pip install -e . 
        python -m pip freeze
    - name: Tests
      shell: "bash -l {0}"
      run: |
        conda activate zarr-env
        pytest --cov=zarr --cov-config=.coveragerc --doctest-plus --cov-report xml --cov=./ 
    - uses: codecov/codecov-action@v1
      with:
        #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          #files: ./coverage1.xml,./coverage2.xml # optional
          #flags: unittests # optional
          #name: codecov-umbrella # optional
          #fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
